### ISSUE TITLE
kudos

### ISSUE THREAD

**Issue by roycewilliams** [magnumripper/headtail#1]
Just wanted to say - brilliant idea, and _very_ useful for some specific, familiar use cases. :grin:

**Comment by magnumripper** [comment]
> Just wanted to say - brilliant idea, and _very_ useful for some specific, familiar use cases. 😁

Cool, spread the word 😉 I've had this idea for years and I already think it's even more useful than I thought.

**Comment by magnumripper** [comment]
BTW I have a related idea of a tool that compresses line width: Any line longer than terminal width will be shown as eg. (for 100 columns terminal width) first 70 chars, then ` (...) ` and then the last 23 chars. Very useful for looking at, for example, a file from `7z2john` with several huge ciphertexts and things like that.

Same functionality could also be added (`-w` option, not default) in headtail.

**Comment by roycewilliams** [comment]
Fantastic idea. Maybe a couple of knob to configure how the compression happens when the max is exceeded for example, by compressing all same-charset sequences into a single book-ended sequence, like replacing '093013013533' with '0..3'

**Comment by magnumripper** [comment]
What would I call such tool (considering a separate one)?

widthcat
catwidth
cattrunc
trunccat
c.t (I kind of love that 🤣)

I think none of the above

**Comment by roycewilliams** [comment]
Since I'd want it specifically in the headtail context, I'd (personally)
rather have it integrated there. :D

**Comment by magnumripper** [comment]
Just for the record I ended up calling it `compcat`, but it's really the same binary morphing when called with that name. It's the same as `headtail -n0 -w`
