### ISSUE TITLE
feature: optional un-HEX

### ISSUE THREAD

**Issue by roycewilliams** [magnumripper/headtail#5]
Would be cool to have a flag to un-HEX $HEX[] notation.. Combined with #4 , this could make for a rich visual display.

**Comment by magnumripper** [comment]
That would be easy but it's feature creep. I use to do it separately with a trivial perl one-liner (as a bash alias), and output can then be piped to this tool... the unix way 😉

**Comment by roycewilliams** [comment]
I encourage you to think beyond the pipeline use case. 😁

Being able to run this on an arbitrary file quickly, while the file is being written to at high speed (for example, if the output is a password cracking tool, the target list is large, and the hash is a fast one) would have significant efficiency value.

**Comment by magnumripper** [comment]
I encourage you to trust the pipeline use case 😉 but unlike what I wrote above you have to convert in the end of the pipline.

`tail -f file | unHEX` should work just fine.

**Comment by magnumripper** [comment]
Here's my crazy one-liner
```
alias unHEX='perl -pe '\''while(m/\$HEX\[([0-9a-f]{2,})\]/){$d=pack("H*",$1);s/\$HEX\[$1\]/$d/}'\'''
```

**Comment by magnumripper** [comment]
OK I see a problem now. Doing `headtail -w | unHEX` would snip line width before lines are unhexed, so will end up with a pessimistic more snip than actually needed.
